language: c
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      before_install: sudo apt-get update -qq && sudo apt-get install -qq libpulse-dev portaudio19-dev libsonic-dev
    - os: osx
      before_install: brew install portaudio

      #branches:
      #  only:
      #    - master


script:
  - ./autogen.sh
  - ./configure
  - make
